#!/bin/bash

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Change to the script's directory
cd "$SCRIPT_DIR"

# Execute the Pandoc command
pandoc "input.pdf" \    # Replace with your input PDF file path
-o "output.pdf" \   # Replace with your output PDF file path
--template="https://raw.githubusercontent.com/maxblumenschein/mdtoanything/refs/heads/main/latex%20templates/linear.latex" \    # Replace with your Latex template file path
--pdf-engine="lualatex" \
--citeproc \
--standalone \
--resource-path="."
