#!/bin/bash

# Get the directory of the script
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Change to the script's directory
cd "$SCRIPT_DIR"

# Execute the Pandoc command
pandoc "INPUT" \
-o "OUTPUT" \
--template="https://raw.githubusercontent.com/maxblumenschein/mdtoanything/refs/heads/main/latex%20templates/linear.latex" \
--pdf-engine="lualatex" \
--citeproc \
--standalone \
--resource-path="."
